### ISSUE TITLE
Android 7.1.1 UnsupportedOperationException - Null

### ISSUE THREAD

**Issue by kenzo23312** [layerhq/Atlas-Android-Messenger#50]
On Android 7.1.1 Nexus 5x - I'm getting such error while authentication process: 
Any ideas how to resolve this ?
`d : Retrying connection in 740 ms due to: null
                                                               java.lang.UnsupportedOperationException
                                                                   at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:482)
                                                                   at java.security.KeyStore.getEntry(KeyStore.java:1323)
                                                                   at com.android.org.conscrypt.KeyManagerImpl.<init>(KeyManagerImpl.java:73)
                                                                   at com.android.org.conscrypt.KeyManagerFactoryImpl.engineGetKeyManagers(KeyManagerFactoryImpl.java:113)
                                                                   at javax.net.ssl.KeyManagerFactory.getKeyManagers(KeyManagerFactory.java:292)
                                                                   at com.layer.transport.auth.d.a(Crypto.java:163)
                                                                   at com.layer.transport.auth.c.<init>(AuthTLSCredentials.java:57)
                                                                   at com.layer.transport.auth.Authentication.j(Authentication.java:196)
                                                                   at com.layer.transport.auth.Authentication.a(Authentication.java:211)
                                                                   at com.layer.transport.lsdkb.b.a(LayerHttp.java:97)
                                                                   at com.layer.transport.lsdkc.k.c(Transport.java:182)
                                                                   at com.layer.sdk.lsdka.lsdkj.e.a(ConnectTask.java:29)
                                                                   at com.layer.sdk.lsdka.lsdkj.e.a(ConnectTask.java:11)
                                                                   at com.layer.lsdka.lsdkc.c.run(RetryableTask.java:156)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                   at java.lang.Thread.run(Thread.java:761)`

**Comment by csbrandt** [comment]
@kenzo23312

If you could please reproduce this issue and capture the logs using instructions at https://docs.layer.com/sdk/android/support, so that we may assist with troubleshooting your issue.

You will receive an email reply confirming that we’ve received your ticket. This will contain a Ticket ID. Please use that ID as reference in any further communication regarding this issue.

**Comment by sriamar** [comment]
This was using an old unsupported version of SDK. Please use the latest one, and the issue should be resolved.

**Comment by jlmcdonnell** [comment]
Still seeing this on Android 8 and Layer SDK version `0.20.3`. I am getting the following log output:

```
11-17 12:54:10.054 8068-8068/? V/LayerSDK: a - 2017-11-17T12:54:10.048 GMT : com.layer.sdk.lsdka.lsdkk.j.c(Log.java:444) : Connecting
11-17 12:54:10.078 8068-8105/? V/LayerSDK: k - 2017-11-17T12:54:10.076 GMT : com.layer.sdk.lsdka.lsdkk.j.c(Log.java:444) : Initializing TLS: Generating CSR
11-17 12:54:10.211 8068-8105/? V/LayerSDK: k - 2017-11-17T12:54:10.210 GMT : com.layer.sdk.lsdka.lsdkk.j.c(Log.java:444) : Initializing TLS: Posting CSR
11-17 12:54:10.353 8068-8068/? V/LayerSDK: a - 2017-11-17T12:54:10.351 GMT : com.layer.sdk.lsdka.lsdkk.j.c(Log.java:444) : App in foreground
11-17 12:54:10.355 8068-8068/? V/LayerSDK: a - 2017-11-17T12:54:10.353 GMT : com.layer.sdk.lsdka.lsdkk.j.c(Log.java:444) : Connecting
11-17 12:54:10.379 8068-8122/? V/LayerSDK: LayerReceiver - 2017-11-17T12:54:10.377 GMT : com.layer.sdk.lsdka.lsdkk.j.c(Log.java:444) : CONNECTION_AVAILABLE
11-17 12:54:10.381 8068-8122/? V/LayerSDK: d - 2017-11-17T12:54:10.379 GMT : com.layer.sdk.lsdka.lsdkk.j.c(Log.java:444) : CONNECTION_AVAILABLE
11-17 12:54:10.885 8068-8105/? V/LayerSDK: k - 2017-11-17T12:54:10.877 GMT : com.layer.sdk.lsdka.lsdkk.j.c(Log.java:444) : Initializing TLS: Saving certificate
11-17 12:54:11.185 8068-8105/? V/LayerSDK: e - 2017-11-17T12:54:11.183 GMT : com.layer.sdk.lsdka.lsdkk.j.c(Log.java:444) : Failed to connect: null
```

I am fairly confident I have followed the getting started steps.
